1-phase PV router: Mk2_fasterControl_Full/FastDivision.cpp File Reference
FastDivision.cpp File Reference
#include "FastDivision.h"
Functions
void divmod10 (uint32_t in, uint32_t &div, uint8_t &mod)
uint16_t divu10 (uint16_t n)
Function Documentation
divmod10()
void divmod10 (uint32_t in, uint32_t & div, uint8_t & mod)
Definition at line 41 of file FastDivision.cpp.
Referenced by configureValueForDisplay(), and test_divmod10().
divu10()
uint16_t divu10 (uint16_t n)
Definition at line 3 of file FastDivision.cpp.
References uint16_t.
Referenced by configureValueForDisplay(), and test_divu10().