1-phase PV router: General Processing
General Processing
Functions and routines that handle general system processing tasks.
Classes
class EWMA_average< A >
Implements an Exponentially Weighted Moving Average (EWMA).
Functions
void logLoadPriorities ()
Prints the load priorities to the Serial output.
void sendResults (bool bOffPeak)
Prints or sends telemetry data logs based on the selected output format.
Detailed Description
Functions and routines that handle general system processing tasks.
This group includes functions that are not time-critical but are essential for the overall operation of the system. These tasks include monitoring system states, managing load priorities, and handling diversion logic.
Functions in this group are typically called from the main loop or other non-interrupt contexts.
They ensure the system operates correctly and adapts to changing conditions.
Function Documentation
logLoadPriorities()
void logLoadPriorities ()
Prints the load priorities to the Serial output.
This function logs the current load priorities and states to the Serial output for debugging purposes. It provides a detailed view of the load configuration and their respective priorities.
Each load's priority and state are printed in a human-readable format.
This function is only active when debugging is enabled (ENABLE_DEBUG).
Definition at line 1362 of file processing.cpp.
References DBUG, DBUGLN, and loadPrioritiesAndState.
Referenced by proceedRotation(), and setup().
sendResults()
void sendResults (bool bOffPeak) inline
Prints or sends telemetry data logs based on the selected output format.
This function handles the transmission of telemetry data in various formats, such as human-readable text, IoT telemetry, or JSON format. It also ensures that the first incomplete datalogging event is skipped during startup.
Parameters
bOffPeak Indicates whether the system is in an off-peak tariff period.
If RF communication is enabled, it sends RF data.
Depending on the SERIAL_OUTPUT_TYPE, it prints data in text format, sends telemetry data, or outputs data in JSON format.
Skips the first datalogging event during startup to avoid incomplete data.
Definition at line 327 of file utils.h.
References HumanReadable, IoT, JSON, printForJSON(), printForSerialText(), sendTelemetryData(), and SERIAL_OUTPUT_TYPE.
Referenced by loop().