1-phase PV router: Mk2_fasterControl_Full/teleinfo.h File Reference
teleinfo.h File Reference
Manages telemetry data and frame formatting.
#include <Arduino.h>
#include "config_system.h"
#include "config.h"
Classes
class TeleInfo
A class for managing and sending telemetry information in a specific frame format.
Functions
static constexpr size_t calcBufferSize ()
Calculates the total buffer size required for the telemetry frame.
static constexpr size_t lineSize (size_t tagLen, size_t valueLen)
Calculates the size of a single telemetry line in the frame.
Detailed Description
Manages telemetry data and frame formatting.
Author
your name (you@d.nosp@m.omai.nosp@m.n.com)
This file defines the TeleInfo class, which is responsible for creating and sending telemetry frames. It includes functions for calculating buffer sizes, formatting data, and ensuring data integrity with checksums.
Frame Structure: Frames start with a Start-of-Text (STX) character and end with an End-of-Text (ETX) character.
Checksum: Ensures data integrity for each line in the frame.
Conditional Features: Supports optional features like relay diversion and temperature sensing.
Version
0.1
Date
2025-04-04
Copyright
Copyright (c) 2025
Definition in file teleinfo.h.
Function Documentation
calcBufferSize()
static constexpr size_t calcBufferSize () inline static constexpr
Calculates the total buffer size required for the telemetry frame.
This function computes the size of the buffer needed to store the entire telemetry frame, including all tags, values, and formatting characters. The calculation takes into account the presence of optional features such as relay diversion and temperature sensing.
Returns
The total buffer size as a compile-time constant.
The buffer size is calculated as follows:
1 byte for the start-of-text (STX) character.
1 line for the "P" tag (signed 6 digits).
For multi-phase systems (NO_OF_PHASES > 1):
NO_OF_PHASES lines for the "R" tag (signed 6 digits each).
NO_OF_PHASES lines for the "V1" tag (unsigned 5 digits each).
For single-phase systems:
1 line for the "D" tag (unsigned 4 digits).
1 line for the "E" tag (unsigned 5 digits).
If relay diversion is enabled (RELAY_DIVERSION):
1 line for the "R" tag (signed 6 digits).
If temperature sensors are present (TEMP_SENSOR_PRESENT):
temperatureSensing.get_size() lines for temperature tags ("T1" to "Tn", 4 digits each).
1 line for the "N" tag (unsigned 5 digits).
1 byte for the end-of-text (ETX) character.
Definition at line 77 of file teleinfo.h.
References lineSize(), NO_OF_DUMPLOADS, NO_OF_PHASES, RELAY_DIVERSION, relays, size(), TEMP_SENSOR_PRESENT, and temperatureSensing.
lineSize()
static constexpr size_t lineSize (size_t tagLen, size_t valueLen) inline static constexpr
Calculates the size of a single telemetry line in the frame.
This function computes the size of a single line in the telemetry frame, including the tag, value, and formatting characters. Each line consists of:
1 byte for the Line Feed (LF) character.
tagLen bytes for the tag.
1 byte for the Tab (TAB) character separating the tag and value.
valueLen bytes for the value.
1 byte for the Tab (TAB) character separating the value and checksum.
1 byte for the checksum.
1 byte for the Carriage Return (CR) character.
Parameters
tagLen The length of the tag in bytes.
valueLen The length of the value in bytes.
Returns
The total size of the line in bytes.
Definition at line 47 of file teleinfo.h.
Referenced by calcBufferSize().