1-phase PV router: Mk2_fasterControl_Full/test/embedded/test_utils_pins/test_main.cpp File Reference
test_main.cpp File Reference
#include <Arduino.h>
#include <U8g2lib.h>
#include <unity.h>
#include "utils_pins.h"
Functions
void loop ()
void setUp (void)
void setup ()
void tearDown (void)
void test_setPinOFF (void)
void test_setPinON (void)
void test_setPinsOFF (void)
void test_setPinsON (void)
void test_setPinState (void)
void test_togglePin (void)
Variables
uint8_t i = 0
uint8_t max_blinks = 2
Detailed Description
Author
Frederic Metrich (frede.nosp@m.ric..nosp@m.metri.nosp@m.ch@l.nosp@m.ive.f.nosp@m.r)
Test
Tests for pins manipulation
Version
0.1
Date
2024-11-15
Copyright
Copyright (c) 2024
Definition in file test_main.cpp.
Function Documentation
loop()
void loop ()
Test
Loop function for running the tests
Definition at line 137 of file test_main.cpp.
References i, max_blinks, test_setPinOFF(), test_setPinON(), test_setPinsOFF(), test_setPinsON(), test_setPinState(), and test_togglePin().
setUp()
void setUp (void)
Test
Set up function for the tests
Definition at line 22 of file test_main.cpp.
setup()
void setup ()
Test
Setup function for the tests
Definition at line 119 of file test_main.cpp.
tearDown()
void tearDown (void)
Test
Tear down function for the tests
Definition at line 30 of file test_main.cpp.
test_setPinOFF()
void test_setPinOFF (void)
Test
Test setting a pin OFF
Definition at line 48 of file test_main.cpp.
References setPinOFF().
Referenced by loop().
test_setPinON()
void test_setPinON (void)
Test
Test setting a pin ON
Definition at line 38 of file test_main.cpp.
References setPinON().
Referenced by loop().
test_setPinsOFF()
void test_setPinsOFF (void)
Test
Test setting multiple pins OFF
Definition at line 103 of file test_main.cpp.
References setPinsOFF().
Referenced by loop().
test_setPinsON()
void test_setPinsON (void)
Test
Test setting multiple pins ON
Definition at line 87 of file test_main.cpp.
References setPinsON().
Referenced by loop().
test_setPinState()
void test_setPinState (void)
Test
Test setting a pin state
Definition at line 74 of file test_main.cpp.
References setPinState().
Referenced by loop().
test_togglePin()
void test_togglePin (void)
Test
Test toggling a pin
Definition at line 58 of file test_main.cpp.
References togglePin().
Referenced by loop().
Variable Documentation
i
uint8_t i = 0
Definition at line 131 of file test_main.cpp.
max_blinks
uint8_t max_blinks = 2
Definition at line 132 of file test_main.cpp.