1-phase PV router: Mk2_fasterControl_Full/utils.h File Reference
utils.h File Reference
Some utility functions.
#include <Arduino.h>
#include <ArduinoJson.h>
#include "FastDivision.h"
#include "calibration.h"
#include "constants.h"
#include "dualtariff.h"
#include "processing.h"
#include "teleinfo.h"
#include "utils_temp.h"
#include "version.h"
Functions
int freeRam ()
Get the available RAM during setup.
void printConfiguration ()
Print the configuration during startup.
void printForJSON (const bool bOffPeak)
Write telemetry data to Serial in JSON format.
void printForSerialText ()
Prints data logs to the Serial output in text format.
void sendResults (bool bOffPeak)
Prints or sends telemetry data logs based on the selected output format.
void sendTelemetryData ()
Sends telemetry data using the TeleInfo class.
Variables
PayloadTx_struct tx_data
Detailed Description
Some utility functions.
Author
Frédéric Metrich (frede.nosp@m.ric..nosp@m.metri.nosp@m.ch@l.nosp@m.ive.f.nosp@m.r)
Version
0.1
Date
2023-02-09
Copyright
Copyright (c) 2023
Definition in file utils.h.
Function Documentation
freeRam()
int freeRam () inline
Get the available RAM during setup.
This function calculates the amount of free RAM available in the system. It is useful for debugging and ensuring that the system has sufficient memory for proper operation.
Returns
int The amount of free RAM in bytes.
Definition at line 366 of file utils.h.
Referenced by setup().
sendTelemetryData()
void sendTelemetryData ()
Sends telemetry data using the TeleInfo class.
This function collects various telemetry data (e.g., power, voltage, temperature, etc.) and sends it in a structured format using the TeleInfo class. The data is sent as a telemetry frame, which starts with a frame initialization, includes multiple data points, and ends with a frame finalization.
The function supports conditional features such as relay diversion, temperature sensing, and different supply frequencies (50 Hz or 60 Hz).
Power Data: Sends the total power grid data.
Relay Data: If relay diversion is enabled (RELAY_DIVERSION), sends the average relay data.
Voltage Data: Sends the voltage data for each phase.
Temperature Data: If temperature sensing is enabled (TEMP_SENSOR_PRESENT), sends valid temperature readings.
Absence of Diverted Energy Count: The amount of seconds without diverting energy.
Note
The function uses compile-time constants (constexpr) to include or exclude specific features. Invalid temperature readings (e.g., OUTOFRANGE_TEMPERATURE or DEVICE_DISCONNECTED_RAW) are skipped.
Exceptions
static_assert If SUPPLY_FREQUENCY is not 50 or 60 Hz.
Definition at line 265 of file utils.h.
References Shared::absenceOfDivertedEnergyCountInSeconds, Shared::copyOf_divertedEnergyTotal_Wh_forDL, Shared::copyOf_lowestNoOfSampleSetsPerMainsCycle, Shared::copyOf_sampleSetsDuringThisDatalogPeriod, DEVICE_DISCONNECTED_RAW, TeleInfo::endFrame(), OUTOFRANGE_TEMPERATURE, RELAY_DIVERSION, relays, TeleInfo::send(), TeleInfo::startFrame(), TEMP_SENSOR_PRESENT, temperatureSensing, and tx_data.
Referenced by sendResults().
Variable Documentation
tx_data
PayloadTx_struct tx_data inline
logging data
Definition at line 37 of file utils.h.
Referenced by loop(), printForJSON(), printForSerialText(), processCalculationsForLogging(), sendTelemetryData(), and updateTemperature().