1-phase PV router: Mk2_fasterControl_Full/validation.h File Reference
validation.h File Reference
#include "config_system.h"
#include "utils_pins.h"
#include "config.h"
Functions
constexpr bool check_load_priorities ()
constexpr uint16_t check_pins ()
constexpr uint16_t check_relay_pins ()
Detailed Description
Author
Frédéric Metrich (frede.nosp@m.ric..nosp@m.metri.nosp@m.ch@l.nosp@m.ive.f.nosp@m.r)
Version
0.1
Date
2024-11-01
Copyright
Copyright (c) 2025
Definition in file validation.h.
Function Documentation
check_load_priorities()
bool check_load_priorities () constexpr
Definition at line 190 of file validation.h.
References bit_read(), bit_set(), loadPrioritiesAtStartup, and NO_OF_DUMPLOADS.
check_pins()
uint16_t check_pins () constexpr
Note
All these checks are done by the compiler. It does not take ANY space in the Arduino.
DO NOT EDIT THIS FILE
Definition at line 49 of file validation.h.
References bit_read(), bit_set(), digitLocationLine, digitSelectionLine, digitSelectorPin, diversionPin, forcePin, physicalLoadPin, RELAY_DIVERSION, relays, rotationPin, SEG, SEG_HW, segmentDrivePin, TEMP_SENSOR_PRESENT, temperatureSensing, TYPE_OF_DISPLAY, and watchDogPin.
check_relay_pins()
uint16_t check_relay_pins () constexpr
Definition at line 169 of file validation.h.
References RELAY_DIVERSION, and relays.